; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Mon Mar 13 2023 20:12:26 GMT+0300 (Москва, стандартное время)
M280 P0 S10 ; deploy BLTouch

