; runonce.g
; called after config.g. When it has been executed, it is automatically deleted!
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Mon Mar 13 2023 20:12:26 GMT+0300 (Москва, стандартное время)
M552 S0                       ; disable network
G4 S5                         ; wait half a second
M587 S"Ufanet_24" P"62021632" ; configure WiFi
G4 S5
M552 S1                       ; enable network
