; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Mon Mar 13 2023 20:12:28 GMT+0300 (Москва, стандартное время)

