; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Mon Mar 13 2023 20:12:29 GMT+0300 (Москва, стандартное время)
; Wait for set temperatures to be reached
M116 P0

